### ISSUE TITLE
Kan de css output vanuit sass netter

### ISSUE THREAD

**Issue by joostf** [kriskuiper/wow-stories#3]

**Comment by joostf** [comment]
De css is nu niet prettig leesbaar

**Comment by kriskuiper** [comment]
Ik voel hier twee opties voor:

1. Helaas het is niet mogelijk
2. Het hele gulp gezeur skippen en gewoon plain css schrijven ipv laten compileren vanuit sass

Ik kom hier morgen bij je op terug

**Comment by kriskuiper** [comment]
Meerdere comments toegevoegd om de css leesbaarder te maken.
