### ISSUE TITLE
form niet een section nesten

### ISSUE THREAD

**Issue by joostf** [kriskuiper/wow-stories#6]
https://github.com/kriskuiper/wow-stories/blob/a6e0a3c762904c7e36bb38cc552c850c8922eb87/src/index.html#L59

form is al een section element

**Comment by kriskuiper** [comment]
Fixed it, heb er een form van gemaakt en de h2 omgezet in een legend binnen de fieldset, dus het wrappen van de sorteeropties in een p is ook gefixt.
